name: dot_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  
  data:
    path: ./packages/data
  services:
    path: ./packages/services

  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/font/Inter-Regular.ttf
  #       - asset: assets/font/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/font/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/font/Inter-Bold.ttf
  #         weight: 700

