name: services
version: 1.0.0+1
publish_to: none
description: Service Packages.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  data:
    path: ../data
  dot_test:
    path: ../../

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.3.8
  http: ^0.13.3
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
